### ISSUE TITLE
Could not run

### ISSUE THREAD

**Issue by ghost** [tlovett1/alexa-skill-test#14]
I am seeing error message:

```
/usr/local/lib/node_modules/alexa-skill-test/node_modules/webpack-dev-middleware/index.js:7
const { getFilenameFromUrl, noop, ready, setFs } = require('./lib/util');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/alexa-skill-test/server.js:7:25)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

```

**Comment by tlovett1** [comment]
Which version of node are you running?

**Comment by tlovett1** [comment]
Need at least node 6.7.
