### ISSUE TITLE
Cannot find module 'webpack-dev-middleware'

### ISSUE THREAD

**Issue by ghost** [tlovett1/alexa-skill-test#5]
Encountered this error while running alexa-skill-test. I have tested for different skills and also
checked the node_modules folder in alexa-skill-test folder and it has webpack-dev-middleware.
Is there anything else I should check?

node version -v -4.4.7
nvm version - v -0.26.1

    Error: Cannot find module 'webpack-dev-middleware'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/qbuser/.nvm/versions/node/v4.4.7/lib/node_modules/alexa-skill-test/server.js:7:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by tlovett1** [comment]
Are you using this is a global npm module?

**Comment by ghost** [comment]
Yes. Installed it using `npm install -g alexa-skill-test`.

**Comment by tlovett1** [comment]
Node 4.7 is required. I fixed package.json.
